#!/bin/bash --login
#$ -cwd
#$ -l nvidia_v100            # Can instead use 'nvidia_a100' for the A100 GPUs (if permitted!)

module load libs/cuda/11.7.0
conda activate ja
# Copy a directory of files from scratch to the GPU node's local NVMe storage
cp -r ~/scratch/PINT/ $TMPDIR

# Process the data with a GPU app, from within the local NVMe storage area
cd $TMPDIR/PINT/
python utils/preprocess_data.py --data wikipedia --bipartite
python preproc.py --data wikipedia --r_dim 4 --data_split train
python preproc.py --data wikipedia --r_dim 4 --data_split val_ind
python preproc.py --data wikipedia --r_dim 4 --data_split val_trans
python preproc.py --data wikipedia --r_dim 4 --data_split test_ind
python preproc.py --data wikipedia --r_dim 4 --data_split test_trans
python preproc.py --data wikipedia --r_dim 4 --data_split join
python train.py --data wikipedia --n_layer 2 --use_memory --beta 0.0001 --n_epoch 50 --patience 5 --n_runs 2 --n_degree 10 --memory_dim 172 --prefix "pint_wikipedia"

# Copy the results back to the main scratch area
rsync -av $TMPDIR/PINT/log/ ~/scratch/PINT/log/
rsync -av $TMPDIR/PINT/results/ ~/scratch/PINT/results/
rsync -av $TMPDIR/PINT/saved_checkpoints/ ~/scratch/PINT/saved_checkpoints/
rsync -av $TMPDIR/PINT/saved_models/ ~/scratch/PINT/saved_models/

# The batch system will automatically delete the contents of $TMPDIR at the end of your job.
cd ~/scratch/PINT/
git pull
git add ./log/
git commit -m "logs updated"
git push

sleep 3
#$ -m ea
#$ -M jiafeng.xiong@manchester.ac.uk,xin.quan@manchester.ac.uk    # Send email when finished.